name: CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Frontend Test
        run: |
          cd frontend
          npm ci || npm install
          npm run test
      - name: Backend Test
        run: |
          cd backend
          npm ci || npm install
          npm test
